export const LOAD_COMPONENTS = 'LOAD_COMPONENTS';
export const CHANGE_EDITING_INDEX = 'CHANGE_EDITING_INDEX';
export const ADD_PLUGIN_COMPONENT = 'ADD_PLUGIN_COMPONENT';

export const UPDATE_PAGE_STYLE = 'UPDATE_PAGE_STYLE';
export const LOAD_PAGE_STYLE = 'LOAD_PAGE_STYLE';

export const LOAD_PAGE_DATA = 'LOAD_PAGE_DATA';
export const SET_PAGE_DATA = 'SET_PAGE_DATA';
export const GET_PAGE_DATA = 'GET_PAGE_DATA';
export const TOGGLE_PREVIEW = 'TOGGLE_PREVIEW';
export const CHANGE_VIEW_MODE = 'CHANGE_VIEW_MODE';
export const TOGGLE_CONTROLLER_MENU = 'TOGGLE_CONTROLLER_MENU';
export const SAVE_PAGE = 'SAVE_PAGE';
export const STORE_PAGES = 'STORE_PAGES';
export const TOGGLE_TITLE_FORM = 'TOGGLE_TITLE_FORM';

export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
